[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

# [profile.Lisk]
# fork_url = "${Lisk_RPC_URL}"
# chain_id = 4202

[profile.lisk_Lisk]
fork_url = "${RPC_URL}"
chain_id = 4202

[etherscan]
# Lisk = { key = "${ETHERSCAN_API_KEY}", url = "https://api-Lisk.etherscan.io/api" }
lisk_Lisk = { key = "123", url = "https://Lisk-blockscout.lisk.com/api" }

[rpc_endpoints]
Lisk = "${Lisk_RPC_URL}"
lisk_Lisk = "${RPC_URL}"

[fmt]
line_length = 100
tab_width = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
